name: deploy

on: workflow_dispatch


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rsync repo to cluster
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          remote_path: ${{ secrets.PATH }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
